import { Metadata } from 'next'
import Script from 'next/script'
import { QRCodeTool } from '@/components/qr-code-tool'

export const metadata: Metadata = {
  title: 'QR Code Generator - Create Custom QR Codes Online',
  description: 'Generate QR codes for URLs, text, emails, phone numbers, WiFi, vCards and more. Customize colors, size, and download in multiple formats. Free and works offline.',
  keywords: 'QR code generator, QR code creator, custom QR codes, WiFi QR, vCard QR, SMS QR',
  openGraph: {
    title: 'QR Code Generator',
    description: 'Create custom QR codes instantly. Works offline, multiple formats supported.',
    url: 'https://www.digitalmix.dev/tools/qr-code-generator',
    type: 'website',
    images: [
      {
        url: 'https://www.digitalmix.dev/og-image.png',
        width: 1200,
        height: 630,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'QR Code Generator',
    description: 'Create custom QR codes instantly. Works offline, multiple formats supported.',
    images: ['https://www.digitalmix.dev/og-image.png'],
  },
  alternates: {
    canonical: 'https://www.digitalmix.dev/tools/qr-code-generator',
    languages: {
      'en-US': 'https://www.digitalmix.dev/tools/qr-code-generator',
    },
  },
}

export default function QRCodeGeneratorPage() {
  const schema = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'SoftwareApplication',
        name: 'QR Code Generator',
        description: 'Free custom QR code generator for URLs, WiFi, vCards, emails, SMS, and plain text',
        url: 'https://www.digitalmix.dev/tools/qr-code-generator',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'Any',
        image: 'https://www.digitalmix.dev/og-image.png',
        featureList: 'Generate custom QR codes for URLs, text, vCard, WiFi, and email; customizable foreground/background colors; high-resolution SVG and PNG exports; 100% offline browser rendering',
        aggregateRating: {
          '@type': 'AggregateRating',
          ratingValue: '4.9',
          ratingCount: '130',
        },
        offers: {
          '@type': 'Offer',
          price: '0',
          priceCurrency: 'USD',
        },
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.digitalmix.dev' },
          { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://www.digitalmix.dev/tools/files' },
          { '@type': 'ListItem', position: 3, name: 'QR Code Generator', item: 'https://www.digitalmix.dev/tools/qr-code-generator' },
        ],
      },
      {
        '@type': 'FAQPage',
        mainEntity: [
          {
            '@type': 'Question',
            name: 'Do the generated QR codes expire?',
            acceptedAnswer: {
              '@type': 'Answer',
              text: 'No, all static QR codes generated by DigitalMix never expire because the data is embedded directly into the QR pattern.',
            },
          },
          {
            '@type': 'Question',
            name: 'Can I download QR codes in vector SVG or PNG format?',
            acceptedAnswer: {
              '@type': 'Answer',
              text: 'Yes, you can export high-resolution PNG images or scalable vector SVG files ready for printing and digital screens.',
            },
          },
          {
            '@type': 'Question',
            name: 'Is it safe to generate WiFi and contact QR codes?',
            acceptedAnswer: {
              '@type': 'Answer',
              text: 'Yes, generation happens 100% locally in your browser memory. Your credentials and passwords are never transmitted over the internet.',
            },
          },
        ],
      },
    ],
  }

  return (
    <>
      <Script
        id="qr-code-generator-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <QRCodeTool />
    </>
  )
}

